# Generated by Django 4.1.7 on 2023-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SN', 'Snacks'), ('JI', 'Jucie Items'), ('BF', 'Breakfast'), ('LH', 'Lunch'), ('ES', 'Evening Snacks'), ('BI', 'Bakery Items'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
